### ISSUE TITLE
Resources are not cleaned up properly

### ISSUE THREAD

**Issue by pihme** [camunda-cloud/camunda-cloud-testing#58]
The following message is printed out during the tests:

```
Nov 15, 2021 8:22:48 PM io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
SEVERE: *~*~*~ Channel ManagedChannelImpl{logId=640, target=0.0.0.0:26500} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
	at io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:93)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:53)
	at io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:44)
	at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:625)
	at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.buildChannel(ZeebeClientImpl.java:130)
	at io.camunda.zeebe.client.impl.ZeebeClientImpl.<init>(ZeebeClientImpl.java:80)
	at io.camunda.zeebe.client.impl.ZeebeClientBuilderImpl.build(ZeebeClientBuilderImpl.java:282)
	at org.camunda.community.eze.ZeebeEngineImpl.createClient(ZeebeEngineImpl.kt:38)
	at EzeExtension$injectFields$2.invoke(EzeExtension.kt:42)
	at EzeExtension$injectFields$2.invoke(EzeExtension.kt:42)
	at EzeExtension.injectFields(EzeExtension.kt:66)
```
Most likely because we don't clean up `ZeebeClient` properly.

**Comment by pihme** [comment]
I tried this in an afterEach callback in the extension:

```
  @Override
  public void afterAll(final ExtensionContext extensionContext) throws Exception {
    final Optional<Field> zeebeClientOptional =
        Arrays.stream(extensionContext.getTestClass().get().getDeclaredFields())
            .filter(field -> ZeebeClient.class.isAssignableFrom(field.getType()))
            .findFirst();
    final Field zeebeClientField = zeebeClientOptional.get();
    ReflectionUtils.makeAccessible(zeebeClientField);
    final Object testInstance = extensionContext.getTestInstance().get();
    final ZeebeClient zeebeClient = (ZeebeClient) zeebeClientField.get(testInstance);

    zeebeClient.close();
  }
```

This fails, because `extensionContext.getTestInstance()` is empty. I think once we reimplement EZE we can also close the Zeebe client in the extension properly. 

I wonder whether this is the reason why builds of GitHub Actions take so long?
